language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 8
  - 7.4snapshot
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

env:
  - WP_VERSION=5.3
  - WP_VERSION=5.2
  - WP_VERSION=5.1
  - WP_VERSION=5.0
  - WP_VERSION=4.9

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - composer install --prefer-dist --no-interaction
